spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studydb?serverTimezone=Asia/Seoul&useSSL=false&autoReconnect=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true&amp;useUnicode=true&characterEncoding=utf8
    username: root
    password: skbaek1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update